### ISSUE TITLE
pcaCODA doesn't work with microbiome data 

### ISSUE THREAD

**Issue by Jayanth-kumar5566** [matthias-da/robCompositions#10]
microbiome dataset usually has a higher number of features than the number of samples. This is causing a problem in the calculation of covariance using MCD.

``
> expenditures<-expenditures[1:4,]
> p1 <- pcaCoDa(expenditures)
Error in robustbase::covMcd(xilr, cor = FALSE) : 
  n <= p -- you can't be serious!
``

**Comment by alexkowa** [comment]
I don't see a possibility to easily extend this to the case of p>n

**Comment by Jayanth-kumar5566** [comment]
I thought so, too. Anyways, I will just implement classical PCA on the ILR coordinates and then transform back.
