### ISSUE TITLE
corCoDa returns NaN Matrix and filtering criteria

### ISSUE THREAD

**Issue by sarpiens** [matthias-da/robCompositions#15]
Hellow, I was working with a set of compositional data (bacterial data):

I had a count matrix of 2399 taxons and 545 samples -> m

This table has many zeros and so I used the cmultRepl function of the zCompositions package to get proportions and handle zeros-> m0=zCompositions::cmultRepl(m, label = 0, method = "CZM"); producing a matrix in proportions with out zeros, were rows are samples and columns are taxons.

When I try to run de corCoDa function, it returns a matrix full of NaN, and 1 in the diagonal -> corCoDa(m0)

If i tried with a subset of 41 taxons of interest, the matrix works and I get correlation values. 

However in some cases these taxons are not the whole composition of the sample:
Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.2379  0.8737  0.9283  0.8970  0.9574  0.9922

My questions:

1) Why does corCoDa return the NaN matrix?

2) Could I filter the proportions table and work only with my subset of interest even if in some samples represent a small part of the sample's composition or would that interfere with the correlation procedure?

Thanks in advance!

**Comment by matthias-da** [comment]
Hello

I'm not the author of the function and the approach, and I do not have reproducible code either to reproduce your example. 

```{r}
library(robCompositions)library(MASS)
x <- mvrnorm(545, m = rep(100,2399), Sigma = diag(2399))
x <- constSum(x)
cc <- corCoDa(x)
```


1. Works with my example. So it must be related with your special setting/data.
2. It would inference the results slightly, as I understood this method. More details Karel could answer you for sure. I gave him in CC. I forwarded this message to him, and he surely will answer in a few days.

**Comment by matthias-da** [comment]
Karel wrote regarding (2): Yes, I do not see any problem if you'll work just with a (well defined) subset of components. You must be only aware that you compute correlations between dominances of parts within a given composition, so the correlation values will (naturally) differ based on that given (sub)composition.

I may close the issue, otherwise - in case you can send us a reproducible example - we can reopen it anytime.
